### ISSUE TITLE
load balancing, failover behaivor, connection pooling support as hector

### ISSUE THREAD

**Issue by ghost** [fluentcassandra/fluentcassandra#1]
Hi,

Great project, thanks for sharing ! Can you please add the features of hector http://github.com/rantav/hector 
I know It's not a simple job and hectorsharp also tried this, but this project seems have more potential.

And I didn't look at the code but EmitMapper http://emitmapper.codeplex.com/ may help for ultra fast mapping and http://fasterflect.codeplex.com/ may help for fast reflection calls to increase performance...

Best Regards, SI

**Comment by managedfusion** [comment]
That has actually been on my hit list, but I really haven't had a chance to figure out the best method for failing over.  Is there an algorithm that you would like to see, or a simple round robin failover, sort of the way that load balancing works, where it just goes through a simple list.

**Comment by ghost** [comment]
Thank you very much for your answer.

I don't know java well but it seems that hector use a simple client list to retry with next on fail (and a sleep before retry) as you can see below...

http://github.com/rantav/hector/blob/master/src/main/java/me/prettyprint/cassandra/service/FailoverOperator.java

**Comment by managedfusion** [comment]
Before I merge in to master, please look at what I have done:  I hope it meets you needs.  It accomplishes the following:
- Failovers
- Connection Pooling
- Load Balancing (random selection from server list)

http://github.com/managedfusion/fluentcassandra/blob/issue-1/FluentCassandra/Connection/NormalConnectionProvider.cs
http://github.com/managedfusion/fluentcassandra/blob/issue-1/FluentCassandra/Connection/PooledConnectionProvider.cs

There are so many types of load balancing, that I just choose the easiest one (random) in hopes it would spark somebody else to give a better or more robust solution.  As far as I could tell, Hector uses a random algorithm for choosing it's load balancing.

**Comment by ghost** [comment]
You're very responsive and super fast and also very kind, thank you very much for your work and sharing it...

Best Regards,
SI

**Comment by managedfusion** [comment]
That didn't really answer my question that I had for you, but I think I am close enough to what you wanted.

**Comment by ghost** [comment]
The code seems very good to me, it's all I have dreamed, thank you very much.

**Comment by ghost** [comment]
This is out of subject, but, is cassandra work on windows as fast as linux, do you have any experience ?

**Comment by managedfusion** [comment]
Cassandra is fully Java based.  So any research you do on Java comparisons will likely apply.

**Comment by ghost** [comment]
thanks again
