### ISSUE TITLE
CRITICAL: CassandraSession.Login() does not work!

### ISSUE THREAD

**Issue by nx-jackal** [fluentcassandra/fluentcassandra#119]
The following code always throw exception during Connection.SetKeyspace() within GetClient() because it tries to select a keyspace before calling login to authenticate.

```
try
{
    this.GetClient (true, null, false).login (auth_request);
    this.IsAuthenticated = true;
}
catch (Exception innerException)
{
    this.IsAuthenticated = false;
    throw new CassandraException ("Login failed.", innerException);
}
```

**Comment by nx-jackal** [comment]
Update that line to the following to allow authentication to pass:

this.GetClient(setKeyspace: false, setLogin: false).login(auth);

**Comment by nberardi** [comment]
Thank you for the pull request.
