### ISSUE TITLE
family.CreateRecord(key: key) doesnt check if BytesType is of 0 length

### ISSUE THREAD

**Issue by razzmatazz** [fluentcassandra/fluentcassandra#12]
Take for example this code:

```
            var family = db.GetColumnFamily<UTF8Type>("report_word_index");

            dynamic record1 = family.CreateRecord("");
            record1.x = 1;
            db.Attach(record1);
            db.SaveChanges();
```

This fails on runtime with <b>"A first chance exception of type 'Apache.Cassandra.InvalidRequestException' occurred in FluentCassandra.dll"</b> exception in Casssandra.cs: public void recv_batch_mutate()

Took me some time to figure out what is wrong (even though it now seems obvious): key is of 0 bytes length.

There should be a better error message and/or exception from fluentcassandra on .CreateRecord() method maybe..

**Comment by nberardi** [comment]
Sorry this has taken so long to respond to.
