### ISSUE TITLE
Enabling authentication and using FluentCassandra to perform insert becomes terribly slow

### ISSUE THREAD

**Issue by nx-jackal** [fluentcassandra/fluentcassandra#121]
After enabling Authenticator in cassandra.yaml using PasswordAuthenticator in cassandra configuration, the record insertion becomes extremely slow.

Unauthenticated insert performance: 2ms-3ms per record insert
Authentication insert performance: 250ms - 280ms per record insert

**Comment by nberardi** [comment]
Thank you for the pull request.

**Comment by nx-jackal** [comment]
Welcome and thank you for actively maintaining this Cassandra driver as OSS project :+1:
