### ISSUE TITLE
Direct Contributors Nomination

### ISSUE THREAD

**Issue by nberardi** [fluentcassandra/fluentcassandra#128]
I am looking for direct contributors to FluentCassandra, my time has been limited recently and I want to advance this project forward, and make sure FluentCassandra will survive in the future.

I have laid a good framework, but I think it is time for me to take a step back and let others advance FluentCassandra that are using it on a daily basis.

I would like you guys to nominate developers who you think can take this project to the next level.  Please submit their GitHub handle below.

**Comment by nberardi** [comment]
I want to nominate @Aaronontheweb and @dlbromen because they have been involved for a long time and seem to understand the project and the direction it is heading.  Anybody else agree?

**Comment by Aaronontheweb** [comment]
@nberardi my availability is somewhat scarce but I'd be happy to lend a hand where possible. let me know what I can do to help.
