### ISSUE TITLE
High CPU utilization when reading with FluentCassandra

### ISSUE THREAD

**Issue by nx-jackal** [fluentcassandra/fluentcassandra#131]
Hi, I notice that spawning multiple threads reading from Cassandra using the driver causes very high CPU load. When scanning through the source, it seems there are many that looks something like:

while(true)
{
//  polling to read or do something else
Thread.Sleep(1); // Can we add this to all the polling loops to reduce CPU usage?
}

I'm not sure how much that will affect the driver performance, perhaps the author can advice on how frequent the iteration occurs and it is advisable to do so? Polling with 'while(true)' without 1ms sleep cycle is choking up the CPU heavily though

**Comment by nberardi** [comment]
Can you please document the places you have found this?
