### ISSUE TITLE
Support for Blob Constant

### ISSUE THREAD

**Issue by tharigopl** [fluentcassandra/fluentcassandra#133]
I cannot find support for the hexadecimal blob constants datatype defined by 0[xX](hex)\+ where hex is an hexadecimal character. Is there any generator like GUID generator. I wrote my own BlobConstant generator for my project. Just wanted to know if FluentCassandra has it.

**Comment by nberardi** [comment]
We would be happy to take a pull request for it.

**Comment by tharigopl** [comment]
Sure. Will complete it.

**Comment by Aaronontheweb** [comment]
@tharigopl the code used for adding the appropriate blob constants in CQL3 can be found in the `CqlHelper` class. From the `CqlHelperTest`:

```
        [Fact]
        public void EscapeBytesForCqlTest()
        {
            //arrange
            var bytes = Encoding.UTF8.GetBytes("hello world");
            var expectedHex = "0x68656c6c6f20776f726c64"; //generated via the textAsBlob function in CQL3 shell

            //act
            var hex = CqlHelper.EscapeForCql(bytes);

            //assert
            Assert.Equal(expectedHex, hex);
        }
```
