### ISSUE TITLE
exception should be thrown when cassandra is down

### ISSUE THREAD

**Issue by LinJiarui** [fluentcassandra/fluentcassandra#137]
when trying "Your First Fluent Cassandra Application" example, if the cassandra is down, it seems that Fluent Cassandra keeps attempting to connect the server, maybe throwing an exception is better choice.

**Comment by Aaronontheweb** [comment]
Cassandra is not SQL Server - you're supposed to run multiple nodes in a production Cassandra cluster, and if one of them goes down it simply gets blacklisted for some period of time until that node is restored.

FluentCassandra will throw an exception after 30s or so after not being able to contact _any_ node, which satisfies your requirement.

**Comment by LinJiarui** [comment]
got it! thanks:)
