### ISSUE TITLE
thrift client throws failed: unknown result or Bad protocol identifier

### ISSUE THREAD

**Issue by lzw88** [fluentcassandra/fluentcassandra#138]
Hi everyone,
    I am using C++ thrift client.
    I am using java thrift server.

I am facing issue C++ client randomly logging:
<service_name> failed: unknown result or Bad protocol identifier

Most of the time calls are working only in some time only that error is
getting logged. What could be the issue here ?

thanks everyone

**Comment by Aaronontheweb** [comment]
Are you actually using FluentCassandra?

**Comment by lzw88** [comment]
No, I am using thrift 0.8.

**Comment by Aaronontheweb** [comment]
Sorry - not sure what your problem might be. You should try StackOverflow or the Thrift mailing list.
