### ISSUE TITLE
Switching build system to Albacore / Rake

### ISSUE THREAD

**Issue by Aaronontheweb** [fluentcassandra/fluentcassandra#140]
@nberardi going to rewrite the NuGet packaging system to an Albacore / Rake-based system if you don't have any objections. We use it for maintaining all of our commercial and OSS NuGet packages and have had great success with it. 

Albacore requires a basic Ruby installation on the target machine but beyond that it's pretty vanilla.

**Comment by nberardi** [comment]
Sounds good to me.

## 

Nick Berardi
(484) 302-0125
Sent on the go from my phone.

On Nov 11, 2013, at 7:21 PM, Aaron Stannard notifications@github.com
wrote:

@nberardi https://github.com/nberardi going to rewrite the NuGet
packaging system to an Albacore / Rake-based system if you don't have any
objections. We use it for maintaining all of our commercial and OSS NuGet
packages and have had great success with it.

Albacore requires a basic Ruby installation on the target machine but
beyond that it's pretty vanilla.

—
Reply to this email directly or view it on
GitHubhttps://github.com/fluentcassandra/fluentcassandra/issues/140
.
