### ISSUE TITLE
Push Latest Code To NuGet

### ISSUE THREAD

**Issue by nberardi** [fluentcassandra/fluentcassandra#141]
Hi @Aaronontheweb 

Thought that having a task might be the easiest first step for us working through the issues of getting you access to NuGet, if there are any issues.

Nick

**Comment by Aaronontheweb** [comment]
@nberardi Nick, yep - I definitely need to push the latest. Planning on sending a pull request this week with an Albacore-based build system to make it easier to package and from there I'll submit the latest to NuGet.
