### ISSUE TITLE
SingleServerManager goes into silent spin-loop on server failure

### ISSUE THREAD

**Issue by sdether** [fluentcassandra/fluentcassandra#144]
`SingleServerManager` silently ignores failures which means tha `NormalConnectionProvider.Open` can never fail but just goes into a spin-loop of retrying connections as fast as possible.

I know there is even a test that makes sure that failure does not impede `SingleServerManager.HasNext` to ever be `false`. However this runs counter to to the behavior of `RoundRobinServerManager` which will eventually return `false` on `HasNext` allowing `Open` to fail.

Unless there is a use-case where a silent spin-loop is actually a desired behavior, I'd like to change `SingleServerManager` to mark its one server as failed for `IConnectionBuilder.ServerPollingInterval` (returning `false` to `HasNext` during the interval), so that Open can fail and the caller can take appropriate action and back-off reconnects.

Let me know if this would be acceptable or what alternate path you'd prefer to allow Single server configurations to detect connect failures, and I'll provide a pull request

**Comment by Aaronontheweb** [comment]
@sdether I was just looking at this source today and wondering the same thing... 

Truth be told: using the SingleServerManager in production is a bad idea given how Cassandra's reliability is built on top of replication and server redundancy, **BUT** as you point out, it should still let you know that something went wrong when it's unable to establish a connection.

I also think that `HasNext` should return false if the single server is unavailable.

Please put together a pull request with these changes - I'll review them and let you know!

**Comment by igorberger** [comment]
Please keep in mind the situation where a single server is a round-robin load balancer address hiding multiple cassandra hosts.

**Comment by nathannis** [comment]
I submitted the SingleServerManager code originally. We are using a load balancer (under a single IP address) to  actually perform the connections.  At the time, the existing code would blacklist our load balancer and just return something about the connection failing without even trying to connect.  Since then, I have found a Datastax recommendation against using a load balancer.  http://www.datastax.com/docs/1.1/cluster_architecture/anti_patterns

The single server implementation is meeting our needs because the load balancer (so far) has always been able to find a cassandra node that is up.

I have noticed that the datastax java driver, when given a single node ip, will look up the other node IPs and do round-robin load balancing automatically.  I can't seem to find such a feature in the Fluent code.

**Comment by sdether** [comment]
@igorberger @nathannis what i can do is maintain the old _"never fail"_ behavior if `IConnectionBuilder.ServerPollingInterval` is set to zero, since that's currently not used for `SingleServerManager` anyway.

**Comment by igorberger** [comment]
Sounds reasonable to me. We don't use a single host. I just remembered the check-in from @nathannis.

**Comment by nberardi** [comment]
Its not implemented. It would probably work best with the round robin.

I think it may make sense remove that silent fail from SingleServerManager
because we shouldn't really be swallowing such a critical error.

And to support custom implementations like Nathans it might be best to have
the ability to swap out the manager instead.

Thoughts.

**Comment by sdether** [comment]
@nberardi I'm in favor of making the manager swappable if that's acceptable.

I was mostly considering the PollingInterval == 0 behavior to maintain existing behavior without change, but since ConnectionBuilder defaults that to 30, the fix to remove the spin-loop would be a breaking change regardless.

I'll add the ability to make the manager swappable and rename the old SingleServerManager implementation so it can be used as a swap in

**Comment by Aaronontheweb** [comment]
@nathannis I believe you're referring to the auto-discovery behavior. This has been discussed before with FluentCassandra. I'm in favor of adding that at some point although there are some major issues with it for people who have their Cassandra instances' rpc_address set to 0.0.0.0 (IPAddress.Any) as they will broadcast both internal and external IPs.

@sdether @nberardi sounds good to me - make the default SingleServerManager expose the critical error and allow it to be swappable sounds like the best approach.

**Comment by sdether** [comment]
Created pull https://github.com/fluentcassandra/fluentcassandra/pull/145 for this change. Looks like the pull is a bit noisy, since my setup uses spaces instead of tabs, vs. the standard. Let me know if i need to figure out how to reformat that or if that's acceptable

**Comment by nberardi** [comment]
Do you happen to have
http://visualstudiogallery.msdn.microsoft.com/dbcb8670-889e-4a54-a226-a48a15e4cace
installed?
 The fix mixed tabs tool is great for auto cleaning these types of problems.

Nick

**Comment by sdether** [comment]
Installed the power tools. Apparently it stepped on some Resharper settings :(

Anyway, pull updated with whitespace fixes

**Comment by Aaronontheweb** [comment]
@sdether thanks for the pull request - will review your submission tomorrow and run your tests. Eyeballed the source and it looks good, but I'll give it a more thorough look tomorrow.

**Comment by Aaronontheweb** [comment]
reviewed code and unit tests today - looks good; accepted pull request. Changes will be included in next release of the NuGet package, which I will do before Christmas.

**Comment by Aaronontheweb** [comment]
Just included this fix in the latest release of FluentCassandra, version v1.2.5 - now live on NuGet.
