### ISSUE TITLE
Followed the First Fluent Cassandra example, but not get through

### ISSUE THREAD

**Issue by JackinLost** [fluentcassandra/fluentcassandra#16]
Hello @nberardi 

I followed "Your First Fluent Cassandra" example, with some modification (the article is creating a super-column, but I only need column), but it gave an exception of Apache.Cassandra.Unavailable. 

It seems the updating is fine, but the exception was given when I try to read(key) after a update.

Could you please have a look at my simple class file? I am using Cassandra 1.0.6 by the way.

Thanks
# 

```
public class CassandraAPI
{
    private CassandraContext cassandraDB;
    private CassandraColumnFamily<BytesType> family;
    public CassandraAPI()
    {
        cassandraDB = new CassandraContext(keyspace: "MyKeyspace", host: "192.168.178.32");
        family = cassandraDB.GetColumnFamily<BytesType>("ColumnFamilyName");

    }

    public void update(byte[] key1, byte[] value)
    {
        dynamic post = family.CreateRecord(key: key1);
        post.value = value;
        // attach the post to the database
        Console.WriteLine("attaching record");
        cassandraDB.Attach(post);

        // save the changes
        Console.WriteLine("saving changes");
        cassandraDB.SaveChanges();
    }

    public void read(byte[] key)
    {
        dynamic getPost = family.Get(key).FirstOrDefault();
        Console.WriteLine("getPost");
        byte[] value = getPost.value;
        Console.WriteLine(value.Length);
    }


}
```

**Comment by nberardi** [comment]
I know it is really out dated and I have to partially apologize for that.  But since that article was written the Cassandra database has had many API changes and other fundamental changes that I just haven't been able to write about them.  To see a working example you can go here:

https://github.com/managedfusion/fluentcassandra/blob/master/test/FluentCassandra.Sandbox/Program.cs
