### ISSUE TITLE
Make A Documentation

### ISSUE THREAD

**Issue by Scentses** [fluentcassandra/fluentcassandra#17]
There is neither a documentation, nor intellisense-aware comments, nor are there any comments in the code. I am stuck at a point, which could be easily passed with only one or two sentences.
Or isn't this project made for public use?

**Comment by nberardi** [comment]
This project is made for public use, but it is also maintained and created by one person with a limited amount of time on his hands. Just keeping up with the constantly changing API of Cassandra is enough for one person. This project is provided for the benefit and consumption by interested developers, and if they derive value from it, I hope that they would contribute back in easy ways such as documentation.

If you want to get a basic idea of how it works and how to use it, please checkout the sandbox project which provides a couple succinct examples.

https://github.com/managedfusion/fluentcassandra/blob/master/test/FluentCassandra.Sandbox/Program.cs
