### ISSUE TITLE
TimeStamp should be switched to Microseconds

### ISSUE THREAD

**Issue by Smoles** [fluentcassandra/fluentcassandra#24]
So I ran into an issue last week were when using a CQL statement to insert a column, letting it implicitly set the TimeStamp, it's using Microseconds. From what I see, FluentCassandra is using Milliseconds and when it tries to read this out of the database it throws an exception. I see you add some code recently to sort of handle this but I don't think the implementation is flawless. As you get closer to 1970 the timestamp will be incorrect because it will no longer divide by 1000 and then start assuming that the value represents Milliseconds instead of Microseconds. Also, using reflection, the AddMilliseconds() method on the DateTimeOffset object with throw an exception if the value to add is greater than 315537897600000.

My understanding is that in the past Milliseconds was the recommended way to store TimeStamps in Cassandra. However, it now seems that the recommendation is to use Microseconds because of it's greater precision. I have been chatting with Matt Denis over at DataStax and he said that most people are switching to Microseconds and that this is also his recommendation.

I propose that FluentCassandra switch to Microseconds as it's default but allow for a config option (as part of the connection string) to indicate the default timestamp storage precision. This way anyone that is currently using Milliseconds can still function but those of us just starting out can start using Microseconds. (Alternatively the default could be Milliseconds for backwards compatibility, with an option to switch to Microseconds).

From my research the best way to calculate Microseconds in .Net is to use Ticks divided by 10. 1 Tick represents 100 Nanoseconds.

**Comment by nberardi** [comment]
I fixed the microseconds throwing an exception by dividing by 1000 when I encounter them.  However most frameworks are storing the Timestamp as Milliseconds or UNIX time.  

https://github.com/managedfusion/fluentcassandra/commit/a307b8e5f8cc938bcc86b1f2bf9c4a265b1adaea#L3R148

I am not sure which is better, to start inserting microseconds from the FluentCassandra framework which would read and write microseconds, or just allow FluentCassandra to support reading them.  What is your opinion?

**Comment by Smoles** [comment]
As I mentioned above I think you should let this be a user decision. Create a config setting (Timestamp Precision) that is set as part of the connection string. When it's set to microseconds then data going in and out of cassandra should be preserved as microseconds. If it's set to milliseconds then it should store and retrieve the value as milliseconds. My assumption is that most people won't have mixed timestamp precision in their Cassandra cluster.

Below is an example of what I'm thinking.

```
    public static long ToTimestamp(this DateTimeOffset dt)
    {
        if (TimestampPrecision == Microseconds)
        {
            return Convert.ToInt64((dt - UnixStart).Ticks / 10);
        }
        else
        {
            return Convert.ToInt64((dt - UnixStart).TotalMilliseconds);
        }
    }

    public static DateTimeOffset FromTimestamp(long ts)
    {

        if (TimestampPrecision == Microseconds)
        {
            return UnixStart.AddTicks(ts * 10);
        }
        else
        {
            return UnixStart.AddMilliseconds(ts);
        }
    }
```

**Comment by nberardi** [comment]
I like to program software with convention over configuration.  So I went with microsecond format since that is the convention that Cassandra is using.
