### ISSUE TITLE
Decimal Issues

### ISSUE THREAD

**Issue by Smoles** [fluentcassandra/fluentcassandra#25]
So I created a table with a default_validation of type decimal. When I use a CQL statement to insert a new column and then attempt to read that column back out, FluentCassandra throws an exception why trying to convert the byte array to a decimal. The exception happens in BytesTypeConvert.ToDecimal().

It seems that the way CQL converts a decimal to a byte array is different then how Fluent is doing it. The length of the byte array varies in size based on the size of the decimal value. It's possible there's a bug in CQL or I'm not representing the decimal correctly in CQL syntax, though I couldn't find anything on DataStax website about this. Below was the CQL I was using.

CREATE TABLE OfferReservation (KEY text PRIMARY KEY) WITH comparator = text AND default_validation = decimal

INSERT INTO OfferReservation (KEY, 'MyColumn') VALUES ('Key1', 0.25)
INSERT INTO OfferReservation (KEY, 'MyColumn') VALUES ('Key2', 2000000000000.1234)

**Comment by nberardi** [comment]
This is a disconnect on how decimals are stored.  .NET expects to always have 16 bytes.  However Java's BigDecimal object can have at the minimum 5 bytes and I don't really know the maximum.

**Comment by nberardi** [comment]
This is a partial fix for this issue.  Negative values aren't supported, but if you want to play around with the binary logic to try and get negative values support that would be very helpful.

**Comment by nberardi** [comment]
Fixed the issue by creating a very crude mock BigDecimal in a similar way to how Java defines it.

https://github.com/managedfusion/fluentcassandra/blob/master/src/Types/BigDecimal.cs
