### ISSUE TITLE
Clear _trackers after db.SaveChanges()

### ISSUE THREAD

**Issue by oliverhuang** [fluentcassandra/fluentcassandra#4]
In the method CassandraContext.SaveChanges(), after saving the changes, you only clear the trackers in _trackers. Why don't you clear the _trackers it self ?

When the size of _trackers is big, Attach() and SaveChanges() will consume very much time...

**Comment by managedfusion** [comment]
Please see latest commit, this should solve the problem.

http://github.com/managedfusion/fluentcassandra/commit/2b16d7fc495015035800d7ae0fdeee21e6c248d4

Nick

**Comment by oliverhuang** [comment]
Thanks!
