### ISSUE TITLE
Expose Time Helper Methods

### ISSUE THREAD

**Issue by Smoles** [fluentcassandra/fluentcassandra#44]
I was wondering if the following methods could be made public. There are a few use cases where it would be helpful to be able to switch back and for between a timestamp in my own code. An example is when you want to set an explicit timestamp on a column when using a CQL query.

FluentCassandra.Operations.Helper.ToTimestamp()
FluentCassandra.Operations.Helper.FromTimestamp()

I think it would also be useful to expose the UnixStart field as public.

Currently the Helper class in marked as internal. I do NOT think it makes sense to make the whole class public. Maybe there's a better location to make these helper type methods to be public? Maybe they could be made into public extension methods.

**Comment by nberardi** [comment]
I agree, I will move the functions that you requested out to the root of FluentCassandra in a static class called TimestampHelper
