### ISSUE TITLE
incorrect mutation being set on super column

### ISSUE THREAD

**Issue by edweip3** [fluentcassandra/fluentcassandra#49]
In the FluentSuperColumn class, the function UpdateParent is calling ResetMutationAndAddAllColumns().  This causes mutations to be added to the tracker for all columns in an existing super column. ResetMutation() should probably be called instead.

steps to reproduce:
1. Create a super column family.
2. insert a row with a super column.
3. update the row to add more super columns using code similar to below

var family = db.GetSuperColumnFamily(ColumnFamilyName);
var record = family.Get(id).FirstOrDefault();

dynamic column = record.CreateSuperColumn();
column.columnname = "column value";
record["supercolumn key"] = column;

db.Attach(record);
db.SaveChanges();

**Comment by nberardi** [comment]
Is there any way you can add a reproduceable test in the Bugs folder. 

https://github.com/managedfusion/fluentcassandra/tree/master/test/FluentCassandra.Tests/Bugs

I tried to get this to happen, but I don't think I am setting it up correctly.  Please feel free to send me a pull request with the test case.

**Comment by edweip3** [comment]
Here's a snippet of code that reproduces the problem.  Sorry, I don't have any spare time right now to do it properly in the Bugs folder.

//create super column family
string ColumnFamilyName = "testfamily";
string key = "somekey";
keyspace.TryCreateColumnFamily(new CassandraColumnFamilySchema
                {
                    FamilyName = ColumnFamilyName,
                    FamilyType = ColumnType.Super,
                    KeyValueType = CassandraType.AsciiType,
                    SuperColumnNameType = CassandraType.AsciiType,
                    ColumnNameType = CassandraType.UTF8Type,
                    DefaultColumnValueType = CassandraType.UTF8Type
                });

//create 1 row with 1 super column  
var family = db.GetSuperColumnFamily(ColumnFamilyName);
var record = family.Get(key).FirstOrDefault();
if (record == null || record.Columns.Count == 0)
{
    record = family.CreateRecord(key: id);
}

var column = record.CreateSuperColumn();
column["columnname"] = "some column value";
column.ColumnName = "supercolumn 1";
record.Columns.Add(column);

db.Attach(record);
db.SaveChanges();  //succeddes.

// create another super column
record = family.Get(key).FirstOrDefault();
if (record == null || record.Columns.Count == 0)
{
    record = family.CreateRecord(key: id);
}

var column2 = record.CreateSuperColumn();
column2["columnname"] = "some other column value";
column2.ColumnName = "supercolumn 2";
record.Column.Add(column2);

db.Attach(record);
db.SaveChanges();  //fails with exception

**Comment by nberardi** [comment]
Nobody has a lot of spare time. If you find value in open source software,
time is how you pay for it.

## 

Nick Berardi
(484) 302-0125
Sent on the go from my phone.

On Aug 22, 2012, at 10:00 AM, edweip3 notifications@github.com wrote:

Here's a snippet of code that reproduces the problem. Sorry, I don't have
any spare time right now to do it properly in the Bugs folder.

//create super column family
string ColumnFamilyName = "testfamily";
string key = "somekey";
keyspace.TryCreateColumnFamily(new CassandraColumnFamilySchema
{
FamilyName = ColumnFamilyName,
FamilyType = ColumnType.Super,
KeyValueType = CassandraType.AsciiType,
SuperColumnNameType = CassandraType.AsciiType,
ColumnNameType = CassandraType.UTF8Type,
DefaultColumnValueType = CassandraType.UTF8Type
});

//create 1 row with 1 super column

var family = db.GetSuperColumnFamily(ColumnFamilyName);
var record = family.Get(key).FirstOrDefault();
if (record == null || record.Columns.Count == 0)
{
record = family.CreateRecord(key: id);
}

var column = record.CreateSuperColumn();
column["columnname"] = "some column value";
column.ColumnName = "supercolumn 1";
record.Columns.Add(column);

db.Attach(record);
db.SaveChanges(); //succeddes.

// create another super column
record = family.Get(key).FirstOrDefault();
if (record == null || record.Columns.Count == 0)
{
record = family.CreateRecord(key: id);
}

var column2 = record.CreateSuperColumn();
column2["columnname"] = "some other column value";
column2.ColumnName = "supercolumn 2";
record.Column.Add(column2);

db.Attach(record);
db.SaveChanges(); //fails with exception

—
Reply to this email directly or view it on
GitHubhttps://github.com/managedfusion/fluentcassandra/issues/49#issuecomment-7934982.

**Comment by nberardi** [comment]
This was fixed with issue #52
