### ISSUE TITLE
Consistency Levels / ConnectionBuilder

### ISSUE THREAD

**Issue by kieranbenton** [fluentcassandra/fluentcassandra#5]
Hi, absolutely love the project and would be interested in contributing on bugs/performance if our usage of Cassandra takes off!

One area which is a bit grey to me at the moment is how to specify the Consistency Levels for both reads and writes. Is this set at creation of the CassandraContext time or per SaveChanges() call?

I'm guessing its the former and these are to be exposed as part of ConnectionBuilder, but haven't been able to find a clue in the source as to how you might be thinking this should be done.

Have you any advice?

Cheers.

**Comment by managedfusion** [comment]
There is actually a new feature in the works that lets you wrap your code in a session.
using(var context = new CassandraContext(...)) {
using(var session = new CassandraSession(read: ConsistencyLevel.ONE, wrote" ConsistencyLevel.ONE)) {
...
}
}

So that you can control the ConsistencyLevel for the read and writes and make them different from the defaults in the connection string.

**Comment by kieranbenton** [comment]
That looks absolutely brilliant!

Have you an idea of how to specify connection pooling / server pools yet? Or is that an area still in flux?

Have you thought about getting a wiki somewhere setup to start some documentation (I could potentially give you a hand). I'm not sure what GitHub offer in that respect?

Cheers,
Kieran

**Comment by nberardi** [comment]
Sorry this took so long to get back to you.

For using Pooled or any of the advanced features you need to create a connection string.  The connection string is pass in the exact same way.  

```
using (var db = new CassandraContext("Keyspace=myspace;Server=10.10.0.1,10.10.0.2;Timeout=5;Pooled=True")) {
}
```

Does this work for you.  I am still working out the algorithm for failover connections.  But pooled should work as expected.

**Comment by kieranbenton** [comment]
Thats perfect.

Is the connection string something standard or is it something you're working on just for this project?

**Comment by nberardi** [comment]
It is just for this project.
