### ISSUE TITLE
Server timeout is lost with default port

### ISSUE THREAD

**Issue by igorberger** [fluentcassandra/fluentcassandra#54]
If "Server" part of connection string doesn't contain a port, Server.Timeout will always be set to 0 in ConnectionBuilder(connectionString). This creates a problem if multiple servers are specified, since the timeout must be non-zero in that case.

**Comment by nberardi** [comment]
I am unable to verify this. Do you gave a test case.

**Comment by igorberger** [comment]
This issue affects single server config as well. E.g., after this code:

```
  var t1 = new ConnectionBuilder("Server=host:123;Connection Timeout=5").Servers[0].Timeout;
  var t2 = new ConnectionBuilder("Server=host;Connection Timeout=5").Servers[0].Timeout;
```

t1 is 5, but t2 is 0.

**Comment by nberardi** [comment]
put Connection Timeout before defining the Servers.  The connection string is currently parsed in order.

**Comment by igorberger** [comment]
Unfortunately that doesn't help. The problem is in this code:

```
if (serverParts.Length == 2)
{
  int port;
  if (Int32.TryParse(serverParts[1], out port))
    Servers.Add(new Server(host: host, port: port, timeout: ConnectionTimeout.Seconds));
  else
    Servers.Add(new Server(host: host, timeout: ConnectionTimeout.Seconds));
}
else
  Servers.Add(new Server(host));
```

When serverParts.Length != 2 (e.g., no port specified), the final _else_ creates a Server object without passing the timeout.

**Comment by nberardi** [comment]
Ok, if you want I do accept pull requests.
