### ISSUE TITLE
Bug in IConnectionProvider.Get(ConnectionBuilder connectionBuilder)

### ISSUE THREAD

**Issue by oliverhuang** [fluentcassandra/fluentcassandra#6]
The 'using (TimedLock.Lock(_lock))' should be in front of 'if (!_providers....)'. 

Lock before checking the existence of provider, to avoid threads conflicts.

**Comment by nberardi** [comment]
You are right, thanks.  I have fixed this issue in the latest commit:

http://github.com/managedfusion/fluentcassandra/commit/f0663287fef6f44b166c7e292e5e596680919485
