### ISSUE TITLE
unable to set cql version at the context level

### ISSUE THREAD

**Issue by gillotte** [fluentcassandra/fluentcassandra#63]
I'm trying to create a table with a composite type key using the syntax similar to 

CREATE TABLE seen_ships (
       day text,
       time_seen timestamp,
       shipname text,
       PRIMARY KEY (day, time_seen)
   );

as explained on http://www.datastax.com/dev/blog/whats-new-in-cql-3-0

getting this snippet to work requires being able to set the CQL version to 3.0.0

```
        using (var db = new CassandraContext(keyspace: KeyspaceName, server: Server))
        {                
            db.ExecuteNonQuery(@"CREATE TABLE seen_ships (
                day text,
                time_seen timestamp,
                shipname text,
                PRIMARY KEY (day, time_seen)
            );");
        }
```

I saw some code that has the functionality partially plummed to set the cql version. So I did a dirty hack for my self, I wouldn't mind flushing it out it if I knew the convention you wished to use.

**Comment by nberardi** [comment]
What do you mean you saw it partially plumed, it is fully plumed as far as I know.  I use it after all.  :)

To get it working you do the following:

``` csharp
        var conn = new ConnectionBuilder(keyspace: KeyspaceName, server: Server, cqlVersion: CqlVersion.Cql3);
        using (var db = new CassandraContext(conn))
        {                
            db.ExecuteNonQuery(@"CREATE TABLE seen_ships (
                day text,
                time_seen timestamp,
                shipname text,
                PRIMARY KEY (day, time_seen)
            );");
        }
```

Specifying connection information in the context is limited to only connecting to the server.  The design is that if you need to do more than just connect to the Cassandra server you need to create a ConnectionBuilder instance and configure it how you want and then pass it in.  The constructors that you are using are really legacy constructors that I cannot remove.  The preferred method is creating the ConnectionBuilder and passing it in.

Nick

**Comment by gillotte** [comment]
ConnectionBuilder(keyspace: KeyspaceName, server: Server, cqlVersion: CqlVersion.Cql3);

was the piece I was missing, I was trying to set it on the context constructor! thanks
