### ISSUE TITLE
CassandraKeyspace.ColumFamilyExists does not work

### ISSUE THREAD

**Issue by sdether** [fluentcassandra/fluentcassandra#69]
Given the below code, CassandraKeyspace.ColumFamilyExists will return false even if ColumnFamily user exists.

``` csharp
using(var db = new CassandraContext(KeyspaceName, Server)) {
    var keyspace = new CassandraKeyspace(new CassandraKeyspaceSchema {
        Name = KeyspaceName,
    }, db);

    if(!keyspace.ColumnFamilyExists("user")) {
        keyspace.TryCreateColumnFamily(new CassandraColumnFamilySchema {
            FamilyName = "user",
            KeyValueType = CassandraType.IntegerType,
            ColumnNameType = CassandraType.UTF8Type,
            DefaultColumnValueType = CassandraType.UTF8Type
        });
    }
}
```

Related, it does seem weird that there are various Try\* methods that all throw. Usual convention is that the Try\* pattern exists to avoid having to catch an exception on failure.

I also tried `var userFamily = db.GetColumnFamily("user");` and checking if userFamily is null, but it always comes back with a value and I cannot determine how you would determine a real value from a synthetic one.

**Comment by nberardi** [comment]
It works as expected.  You provided a schema to it, instead of letting it pull it from the database.  So in the schema that you provided you didn't define a ColumnFamily called "user".  So this isn't a bug, just a programming error.  If you would like it to work do the following.

``` csharp
using(var db = new CassandraContext(KeyspaceName, Server)) {
    var keyspace = db.Keyspace;

    if(!keyspace.ColumnFamilyExists("user")) {
        keyspace.TryCreateColumnFamily(new CassandraColumnFamilySchema {
            FamilyName = "user",
            KeyValueType = CassandraType.IntegerType,
            ColumnNameType = CassandraType.UTF8Type,
            DefaultColumnValueType = CassandraType.UTF8Type
        });
    }
}
```

In your CassandraContext you must have ThrowErrors set to true.  This probably is going to be changing soon, so if you don't want Try\* to throw errors just disable the ThrowErrors property.  This is a known sore point, and it will be changing with the next major release.

**Comment by nberardi** [comment]
Opened so you could comment. I closed by accident.

**Comment by sdether** [comment]
Thx. Was working off the examples and did not understand the significance of how keyspace was constructed in the example.

**Comment by nberardi** [comment]
No problem.

**Comment by sdether** [comment]
BTW, still curious why Try\* methods throw rather than return a bool as is usual.

**Comment by nberardi** [comment]
Read paragraph under code in my original response.

**Comment by sdether** [comment]
Sorry about that. Must have just seen the code and skipped reading the rest :) Thanks for the info.
