### ISSUE TITLE
counter columns

### ISSUE THREAD

**Issue by ilushka85** [fluentcassandra/fluentcassandra#71]
how do we increment / decrement counter columns?

**Comment by nberardi** [comment]
That hasn't been implemented. If you are interested in sending me a pull
request I will not object.

## 

Nick Berardi
(484) 302-0125
Sent from my tablet.

On Oct 8, 2012, at 12:01 PM, ilushka85 notifications@github.com wrote:

how do we increment / decrement counter columns?

—
Reply to this email directly or view it on
GitHubhttps://github.com/managedfusion/fluentcassandra/issues/71.

**Comment by ilushka85** [comment]
Is it merely the thrift add command on counter columns ?

Sent from my iPhone

On Oct 8, 2012, at 12:39 PM, Nick Berardi notifications@github.com wrote:

That hasn't been implemented. If you are interested in sending me a pull
request I will not object.

## 

Nick Berardi
(484) 302-0125
Sent from my tablet.

On Oct 8, 2012, at 12:01 PM, ilushka85 notifications@github.com wrote:

how do we increment / decrement counter columns?

—
Reply to this email directly or view it on
GitHubhttps://github.com/managedfusion/fluentcassandra/issues/71.

—
Reply to this email directly or view it on
GitHubhttps://github.com/managedfusion/fluentcassandra/issues/71#issuecomment-9233779.

**Comment by nberardi** [comment]
Yes it is.  Which I have implemented in FluentCassandra as a straight RPC
command.  However there is not support in the fluent-part of the library.
 You can use it by doing the following:

https://github.com/managedfusion/fluentcassandra/blob/master/src/CassandraColumnFamilyOperations.cs#L59

columnFamily.InsertCounterColumn(key, columnName, longValue);

However, I don't know if I like the name.  Didn't really like AddColumn
either.  Maybe IncrementCounterColumn?  What do you think?

Nick

**Comment by nberardi** [comment]
Don't think I am going to tackle this in the fluent part.

**Comment by eplowe** [comment]
Yeah it seems really fuzzy how the actual implementation would look.
