### ISSUE TITLE
.TakeKeys not returning proper record count

### ISSUE THREAD

**Issue by ilushka85** [fluentcassandra/fluentcassandra#72]
Specifying .TakeKeys() while using start key does not return proper amount of keys

``` csharp
var usersTest1 = usersColumnFamily.Get()
    .StartWithKey("").TakeUntilKey("").TakeKeys(150)
    .Execute();

var usersTest2 = usersColumnFamily.Get()
    .StartWithKey("").TakeUntilKey("").TakeKeys(150)
    .Where(t => t["IsConfirmed"] == false.ToString())
    .Execute();
```

userstest1 returns 150 keys as indicated
userstest2 returns 100 keys

the problem in code is the following file:  `CassandraSlicePredicateBuilder.cs`

Line 151 says 

``` csharp
var indexClause = new CassandraIndexClause(setup.StartKey, setup.ColumnCount, setup.IndexClause);
```

in realtiy the indexclause should be given the count of how many keys we want so the correct line should be

``` csharp
var indexClause = new CassandraIndexClause(setup.StartKey, setup.KeyCount, setup.IndexClause);
```

Can someone create a patch for this?

**Comment by nberardi** [comment]
Any chance you can send a pull request with the updated code.

## 

Nick Berardi
(484) 302-0125
Sent on the go from my phone.

On Oct 8, 2012, at 8:31 PM, ilushka85 notifications@github.com wrote:

var usersTest1 =
usersColumnFamily.Get().StartWithKey("").TakeUntilKey("").TakeKeys(150)..Execute();

var usersTest2 =
usersColumnFamily.Get().StartWithKey("").TakeUntilKey("").TakeKeys(150).Where(t
=> t["IsConfirmed"] == false.ToString()).Execute();

userstest1 returns 150 keys as indicated

userstest2 returns 100 keys

the problem in code is the following file: CassandraSlicePredicateBuilder.cs

Line 151 says

var indexClause = new CassandraIndexClause(setup.StartKey,
setup.ColumnCount, setup.IndexClause);

in realtiy the indexclause should be given the count of how many keys we
want so the correct line should be

var indexClause = new CassandraIndexClause(setup.StartKey, setup.KeyCount,
setup.IndexClause);

Can someone create a patch for this?

—
Reply to this email directly or view it on
GitHubhttps://github.com/managedfusion/fluentcassandra/issues/72.
