### ISSUE TITLE
Connection pool not getting cleaned up on first socket error

### ISSUE THREAD

**Issue by igorberger** [fluentcassandra/fluentcassandra#80]
When my process loses connection to a Cassandra node,
it takes 2 failed requests to clean up connection pool.

Since FluentCassandra already detects lost connectivity, closing the socket
will allow to clean up connection pool after the first failed request.

A simple fix is to add "this.Close();" inside of "if (ret <= 0)" in TTransport.ReadAll().

Running version 1.1.8. Sorry, I can't create a pull request.

Scenario:
1. ConnectionBuilder is initialized with multiple server nodes and pooling turned on.
2. A request to Cassandra succeeds and the session is released, leaving a socket
   connected to the first Cassandra node in PooledConnectionProvider._freeConnections.
3. This Cassandra node is restarted. The socket goes into CLOSE_WAIT state.
4. Second request runs. TFramedTransport.Read() returns 0, which causes
   TTransport.ReadAll() to throw TTransportException. (Callstack 1 below)
5. My application code releases the session, calling PooledConnectionProvider.Close().
   Since IsAlive(connection) still returns true, this connection is re-added to _freeConnections.
6. Third request runs. "outputStream.Write()" in TStreamTransport.Write()
   throws SocketException. (Callstack 2 below)
7. My application code releases the session, calling PooledConnectionProvider.Close().
   This time IsAlive(connection) returns false. _freeConnections remains empty.
8. Fourth request runs. Since there are no free connections,
   a new one is created to the next Cassandra node.
## Callstack 1

FluentCassandra.dll!Thrift.Transport.TTransport.ReadAll(byte[] buf, int off, int len) Line 57
FluentCassandra.dll!Thrift.Transport.TFramedTransport.ReadFrame() Line 89 + 0x1a bytes
FluentCassandra.dll!Thrift.Transport.TFramedTransport.Read(byte[] buf, int off, int len) Line 81 + 0x8 bytes
FluentCassandra.dll!Thrift.Transport.TTransport.ReadAll(byte[] buf, int off, int len) Line 53 + 0x1c bytes
FluentCassandra.dll!Thrift.Protocol.TBinaryProtocol.ReadAll(byte[] buf, int off, int len) Line 391 + 0x1c bytes
FluentCassandra.dll!Thrift.Protocol.TBinaryProtocol.ReadI32() Line 337 + 0x18 bytes
FluentCassandra.dll!Thrift.Protocol.TBinaryProtocol.ReadMessageBegin() Line 220 + 0xa bytes
FluentCassandra.dll!Apache.Cassandra.Cassandra.Client.recv_set_keyspace() Line 137 + 0x11 bytes
FluentCassandra.dll!Apache.Cassandra.Cassandra.Client.set_keyspace(string keyspace) Line 122 + 0x8 bytes
FluentCassandra.dll!FluentCassandra.Connections.Connection.SetKeyspace(string keyspace) Line 169 + 0x18 bytes
FluentCassandra.dll!FluentCassandra.CassandraSession.GetClient(bool setKeyspace, bool? setCqlVersion) Line 109 + 0x2d bytes
FluentCassandra.dll!FluentCassandra.CassandraKeyspace.GetSchema.AnonymousMethod__a(FluentCassandra.Operations.SimpleOperation<Apache.Cassandra.KsDef> ctx) Line 144 + 0x29 bytes
FluentCassandra.dll!FluentCassandra.Operations.SimpleOperation<Apache.Cassandra.KsDef>.Execute() Line 17 + 0x11 bytes
FluentCassandra.dll!FluentCassandra.Operations.Operation<Apache.Cassandra.KsDef>.TryExecute(out Apache.Cassandra.KsDef result) Line 24 + 0x11 bytes
FluentCassandra.dll!FluentCassandra.CassandraSession.ExecuteOperation<Apache.Cassandra.KsDef>(FluentCassandra.Operations.Operation<Apache.Cassandra.KsDef> action, bool? throwOnError) Line 185 + 0xe bytes
FluentCassandra.dll!FluentCassandra.CassandraContext.ExecuteOperation<Apache.Cassandra.KsDef>(FluentCassandra.Operations.Operation<Apache.Cassandra.KsDef> action, bool? throwOnError) Line 383 + 0xc5 bytes
FluentCassandra.dll!FluentCassandra.CassandraKeyspace.GetSchema() Line 143 + 0x8a bytes
FluentCassandra.dll!FluentCassandra.CassandraKeyspace.GetColumnFamilySchema(string columnFamily, bool onlyCheckCache) Line 123 + 0x8 bytes
FluentCassandra.dll!FluentCassandra.CassandraContext.GetColumnFamily(string columnFamily) Line 80 + 0x1a bytes

---
## Callstack 2

System.dll!System.Net.Sockets.Socket.Send(byte[] buffer, int offset, int size, System.Net.Sockets.SocketFlags socketFlags) + 0x5a bytes 
System.dll!System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size) + 0x87 bytes 
FluentCassandra.dll!Thrift.Transport.TStreamTransport.Write(byte[] buf, int off, int len) Line 94 + 0x1d bytes
FluentCassandra.dll!Thrift.Transport.TFramedTransport.Flush() Line 123 + 0x1c bytes
FluentCassandra.dll!Apache.Cassandra.Cassandra.Client.send_set_keyspace(string keyspace) Line 132 + 0x1b bytes
FluentCassandra.dll!Apache.Cassandra.Cassandra.Client.set_keyspace(string keyspace) Line 121 + 0xb bytes
FluentCassandra.dll!FluentCassandra.Connections.Connection.SetKeyspace(string keyspace) Line 169 + 0x18 bytes
FluentCassandra.dll!FluentCassandra.CassandraSession.GetClient(bool setKeyspace, bool? setCqlVersion) Line 109 + 0x2d bytes
FluentCassandra.dll!FluentCassandra.CassandraKeyspace.GetSchema.AnonymousMethod__a(FluentCassandra.Operations.SimpleOperation<Apache.Cassandra.KsDef> ctx) Line 144 + 0x29 bytes
FluentCassandra.dll!FluentCassandra.Operations.SimpleOperation<Apache.Cassandra.KsDef>.Execute() Line 17 + 0x11 bytes
FluentCassandra.dll!FluentCassandra.Operations.Operation<Apache.Cassandra.KsDef>.TryExecute(out Apache.Cassandra.KsDef result) Line 24 + 0x11 bytes
FluentCassandra.dll!FluentCassandra.CassandraSession.ExecuteOperation<Apache.Cassandra.KsDef>(FluentCassandra.Operations.Operation<Apache.Cassandra.KsDef> action, bool? throwOnError) Line 185 + 0xe bytes
FluentCassandra.dll!FluentCassandra.CassandraContext.ExecuteOperation<Apache.Cassandra.KsDef>(FluentCassandra.Operations.Operation<Apache.Cassandra.KsDef> action, bool? throwOnError) Line 383 + 0xc5 bytes
FluentCassandra.dll!FluentCassandra.CassandraKeyspace.GetSchema() Line 143 + 0x8a bytes
FluentCassandra.dll!FluentCassandra.CassandraKeyspace.GetColumnFamilySchema(string columnFamily, bool onlyCheckCache) Line 123 + 0x8 bytes
FluentCassandra.dll!FluentCassandra.CassandraContext.GetColumnFamily(string columnFamily) Line 80 + 0x1a bytes

---

**Comment by nberardi** [comment]
Why can't you create a pull request?  I would like to review your change, and let everybody else here review it too.  I think it is a good one.

**Comment by igorberger** [comment]
The amount of effort needed to go through the corporate process of contributing to open source (without getting reprimanded and without having to worry about license issues) is disproportionate to just making this change locally and making sure it's not lost in the future.

I'm just trying to contribute _something_ back.

**Comment by nberardi** [comment]
You are asking to modify a library defined by http://thrift.apache.org/ this is the one source that I don't modify the code.  For one because it is becoming irreverent in more recent versions of Cassandra and for two, it is another companies library, so the bug should really be submitted to them.  I would be willing to entertain a solution that happened in the FluentCassandra code.

**Comment by nberardi** [comment]
I am closing this one since, there is nothing I can do about the Thrift API.  Also there is already an issue about the connection pool in Issue #29.  I know any insight would be appreciated by the people watching that thread.
