### ISSUE TITLE
describe_keyspace failed: unknown result --->  Thrift.TapplicationException:

### ISSUE THREAD

**Issue by ilushka85** [fluentcassandra/fluentcassandra#81]
We periodically get this error.  What could be the cause of it?   Why do we need to even run a describe keyspace before execution?

FluentCassandra.CassandraException: describe_keyspace failed: unknown result ---> Thrift.TApplicationException: describe_keyspace failed: unknown result
   at Apache.Cassandra.Cassandra.Client.recv_describe_keyspace() in c:\B\1\S\Clarity\FluentCassandra\Apache\Cassandra\Cassandra.cs:line 1065
   at FluentCassandra.CassandraKeyspace.<GetSchema>b__a(SimpleOperation`1 ctx) in c:\B\1\S\Clarity\FluentCassandra\CassandraKeyspace.cs:line 144
   at FluentCassandra.Operations.Operation`1.TryExecute(TResult& result) in c:\B\1\S\Clarity\FluentCassandra\Operations\Operation.cs:line 24

**Comment by nberardi** [comment]
My guess with out knowing more is that you received back a garbled response
from Cassandra for a schema request.  This happens when Cassandra throws an
error that it hasn't defined in it's protocol.

https://github.com/managedfusion/fluentcassandra/blob/master/src/Apache/Cassandra/Cassandra.cs#L1065

What version of Cassandra are you using?

**Comment by ilushka85** [comment]
1.1.5  -  Whats stange is calling the function once the data loads fine.... second time we call it this error happens --- totally random in that regard in the same function.

But second part of question is why do we need to even call describe?

**Comment by nberardi** [comment]
The schema is needed to properly encode the columns to the right type.
 When you query Cassandra everything comes back as a byte array, and then
through some magic (mainly using the schema) FluentCassandra understands
how to convert that byte array into the types and vice versa when you are saving your changes to Cassandra

**Comment by ilushka85** [comment]
Yes but if we explicitly define the column family like:

public CassandraColumnFamily<LongType>  test = CreateColumnFamily<LongType>("test");

Why would it need to ever call getscema?

**Comment by nberardi** [comment]
I am not quite sure what that code is doing.  Are you using `Keyspace.TryCreateColumnFamily`? I am curious to the actual code, since get schema is never called when creating a column family, because the schema is provided on creation, so there is no need to call the describe_keyspace.

**Comment by ilushka85** [comment]
Right.... this is the code i used to to create the column family .... let i run some query against this object by doing .get and some other calls... those are the ones that call the describe_keyspace:

If you look at the stack trace from my first msg you will see the describe_keyspace is being called by TryExecute

It doesnt make sense for it to call it though since ive explicitly defined the column family

**Comment by nberardi** [comment]
My guess is that you only defined the name and not the schema.  If you don't want it to do a lookup you have to define the schema.  If you just provide a name it does a lookup on the schema.

**Comment by ilushka85** [comment]
How would you define the schema if its not in the way i showed above?

**Comment by nberardi** [comment]
You didn't show real code, so I don't know how you would define it.  Please show you actual code and I can help.

**Comment by ilushka85** [comment]
``` csharp
public CassandraColumnFamily<UTF8Type> _jobTypesCF = null;
_jobTypesCF = CreateColumnFamily<UTF8Type>("JobTypes");
GetAllRows(_jobTypesCF);
```

Above is what im Executing.

the GetAllRows Function:

``` csharp
 protected List<FluentColumnFamily> GetAllRows(CassandraColumnFamily fromColumnFamily, int blockSize = 50)
        {
            try
            {
                List<FluentColumnFamily> rows = new List<FluentColumnFamily>();
                List<FluentColumnFamily> partialRows = null;

                bool isFirstLoop = true;




                do
                {

                    if (isFirstLoop)
                    {
                        partialRows = fromColumnFamily.Get().StartWithKey("").TakeUntilKey("").TakeKeys(blockSize).NullOrToList();
                    }
                    else
                    {
                        partialRows = fromColumnFamily.Get().StartWithKey(partialRows.Last().Key).TakeUntilKey("").TakeKeys(blockSize).NullOrToList();
                    }

                    if (partialRows.IsNullOrEmpty()) break;

                    rows.AddRange(isFirstLoop ? partialRows : partialRows.Skip(1));
                    isFirstLoop = false;
                }
                while (!partialRows.IsNullOrEmpty() && partialRows.Count > 1);

                return rows;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
```

**Comment by nberardi** [comment]
Can you please show `CreateColumnFamily` nothing else matters.

**Comment by ilushka85** [comment]
Sorry i copied and pasted wrong:   

_jobTypesCF = CreateColumnFamily<UTF8Type>("JobTypes");

CreateColumnFamily is a fluent function

**Comment by ilushka85** [comment]
If you examine it further it ends up calling this:

public class CassandraColumnFamily<CompareWith> : CassandraColumnFamily
        where CompareWith : CassandraObject
    {
        public CassandraColumnFamily(CassandraContext context, string columnFamily)
            : base(context, columnFamily)
        {
            SetSchema(new CassandraColumnFamilySchema {
                FamilyName = columnFamily,
                ColumnNameType = typeof(CompareWith)
            });
        }
    }

**Comment by nberardi** [comment]
Use the other constructor for `CassandraColumnFamily` instead.

``` csharp
        public CassandraColumnFamily(CassandraContext context, CassandraColumnFamilySchema schema)
            : base(context, schema.FamilyName)
        {
            _cachedSchema = schema;
        }
```

Also that is what confused me `CreateColumnFamily` isn't a function from FluentCassandra it must be defined in your code somewhere.  You need to use the other constructor which takes a schema, if one isn't provided, it is looked up from the server.

**Comment by ilushka85** [comment]
You are right about it not being part of fluent... heres its code:

  protected CassandraColumnFamily<CompareWith> CreateColumnFamily<CompareWith>(string CFName)
            where CompareWith : CassandraObject
        {
            return new CassandraColumnFamily<CompareWith>(db, CFName);
        }

This in turn calls CassandraColumnFamily<CompareWith>    which is a function of fluent and sets the schema:

[Obsolete("Use \"CassandraColumnFamily\" class with out generic type")]
    public class CassandraColumnFamily<CompareWith> : CassandraColumnFamily
        where CompareWith : CassandraObject
    {
        public CassandraColumnFamily(CassandraContext context, string columnFamily)
            : base(context, columnFamily)
        {
            SetSchema(new CassandraColumnFamilySchema {
                FamilyName = columnFamily,
                ColumnNameType = typeof(CompareWith)
            });
        }
    }

**Comment by nberardi** [comment]
Switch to the non generic form.  That class is now obsolete.  

The change to schema's happened at the same time these classes were obsoleted, because it was no longer possible to support generics with all the changes being made to the Cassandra server.

**Comment by ilushka85** [comment]
Yes but their code is functionally the same still.

**Comment by nberardi** [comment]
Found the issue this will be released with the next update.

**Comment by ilushka85** [comment]
I found the issue.... there is a mistake in CassandraColumnFamily.cs

public override CassandraColumnFamilySchema GetSchema()
        {
            var schema = Context.Keyspace.GetColumnFamilySchema(FamilyName);

```
        if (_cachedSchema == null)
            _cachedSchema = (schema == null)
                ? new CassandraColumnFamilySchema(FamilyName, ColumnType.Standard)
                : schema;

        return _cachedSchema;
    }
```

this function calls 

Context.Keyspace.GetColumnFamilySchema(FamilyName);

public CassandraColumnFamilySchema GetColumnFamilySchema(string columnFamily, bool onlyCheckCache = false)
        {
            if (onlyCheckCache && _cachedSchema == null)
                return null;

```
        return GetSchema().ColumnFamilies.FirstOrDefault(cf => cf.FamilyName == columnFamily);
    }
```

_cachedSchema is null here since its relying on keyspace schema instead of column family schema.

If keyspace schema isnt cached then we get the full keyspace schema rather then just column family schema to execute the function.  This makes no sense.

Easy fix is to move the call to after the check if cachedSchema is null

like:

```
public override CassandraColumnFamilySchema GetSchema()
    {



        if (_cachedSchema == null)
        {
            var schema = Context.Keyspace.GetColumnFamilySchema(FamilyName);
            _cachedSchema = (schema == null)
                            ? new CassandraColumnFamilySchema(FamilyName, ColumnType.Standard)
                            : schema;
        }

        return _cachedSchema;
    }
```

**Comment by ilushka85** [comment]
Thats funny we got same solution at same time.

**Comment by nberardi** [comment]
Already did that see last comment.

**Comment by nberardi** [comment]
So this will be released with the next release, which I usually try to batch up a bunch of updates.  So I don't know when this will hit the street, but it will probably be version 1.1.10.  

Until then, I would investigate why your Cassandra server doesn't like describing the same keyspace twice, because I have never seen this issue.

**Comment by ilushka85** [comment]
Its actually a substantial performance hit on apps that are web based as its constantly new contexts and such where they arent cached after first time.

**Comment by ilushka85** [comment]
Can you include the update (i didnt submit a pull request as im unfamiliar with git) but the code is posted in my other issue:  #72

**Comment by nberardi** [comment]
The way that you are doing it with the old interface looses allot of the schema, so I would advise you updating it.  Secondly, sending pull requests is very easy, and you don't need to know GIT to use GitHub, you can use the Web UI or SVN if you don't like the GIT protocol.

https://github.com/blog/1178-collaborating-on-github-with-subversion

Here is a guide on how to create a pull request.

https://help.github.com/articles/creating-a-pull-request

Please move any comments about #72 to that thread.
