### ISSUE TITLE
BigDecimal is incorrect

### ISSUE THREAD

**Issue by woolfel** [fluentcassandra/fluentcassandra#83]
The way cassandra stores and uses BigDecimal is reverse from what you have. The first 4 bytes is the scale and the remaining bytes are the BigInteger.

http://grepcode.com/file/repo1.maven.org/maven2/org.apache.cassandra/cassandra-all/1.0.0-rc2/org/apache/cassandra/cql/jdbc/JdbcDecimal.java

Even though this will store properly for .Net, the minute someone tries to use cassandra-cli or cqlsh, it will result in java heap space error and crash. If people are reading data from other platforms like java or python, it will be wrong.

**Comment by nberardi** [comment]
Please review the byte output to make sure that they are in the proper order and the sections are facing the right way for their endianess. 

``` csharp
private readonly BigDecimal bigDecimal = 100002334.4563D;
private readonly byte[] dotNetByteOrder = new byte[] { 179, 69, 9, 214, 232, 0, 4, 0, 0, 0 };
private readonly byte[] javaByteOrder = new byte[] { 0, 0, 0, 4, 0, 232, 214, 9, 69, 179 };
```

This is taken from the following test, please update the test with the correct values if the assumptions are wrong.

https://github.com/managedfusion/fluentcassandra/commit/d05b40e1a58f2a6c466c71bd51232d5272938512#diff-6

**Comment by nberardi** [comment]
Closing since there hasn't been any response.
