### ISSUE TITLE
Connection Pooling is Blacklisting too aggressively

### ISSUE THREAD

**Issue by tjake** [fluentcassandra/fluentcassandra#85]
We had a network issue that caused all connections to hiccup. 

FluentCassandra subsequently blacklisted all the servers in the connection pool.  This logic should account for this, perhaps the blacklist entries should expire after N minutes and/or connections should be blacklisted after N failures.  Also it should avoid blacklisting all servers.

**Comment by nberardi** [comment]
Merging into issue #51
