### ISSUE TITLE
1.1.10 - Exception while CQL Delete row - "object not set to an instance of an object" 

### ISSUE THREAD

**Issue by okarmi** [fluentcassandra/fluentcassandra#91]
After upgrading to 1.1.10 (from 1.1.9) I started getting an exception while sending a CQL Delete command.

I reverted to 1.1.9 and the exception was gone, upgrading to 1.1.10 again returned the exception.

Exception - "object not set to an instance of an object" seems to originate from
CassandraCqlRowSchema(CqlResult result, string familyName) because result.Schema is null.

The delete query does work (line is deleted from table).

Simple code example:

```
            CQLString = "DELETE FROM CFTest  WHERE KeyUID IN ('" + m_KeyUID + "');";

            using (CassandraContext db = new CassandraContext(m_ConnectionObject))
            {
                try
                {
                    db.ExecuteQuery(CQLString);
                }
                catch (System.Exception ex)
                {

                }
            }
```

**Comment by eplowe** [comment]
use ExecuteNonQuery instead of ExecuteQuery when doing
insert/update/deletes.

**Comment by nberardi** [comment]
I am closing this since it appears to be related to what @eplowe mentioned.
