### ISSUE TITLE
Automatic Server Discovery

### ISSUE THREAD

**Issue by eplowe** [fluentcassandra/fluentcassandra#92]
Just creating a place holder issue for the server discovery enhancements I've made. I've also retooled the concept of the ServerManager and how it's implemented. I've been busy with the day job so I missed my original self imposed deadline... but it should be available for review before the new year.

**Comment by Aaronontheweb** [comment]
@eplowe any word on this? Seems like a great set of improvements :)

**Comment by eplowe** [comment]
I have a branch working but my day job has kept me very busy and I haven't
had time to go back and properly test, etc.

**Comment by eplowe** [comment]
Closing this issue as there doesn’t seem to be much steam behind fluentcassandra.
