### ISSUE TITLE
Anybody Know Anything About These Types

### ISSUE THREAD

**Issue by nberardi** [fluentcassandra/fluentcassandra#97]
I like to maintain a pretty complete list of types in FluentCassandra, but I have to admit I know nothing about the following types:
- LocalByPartitionerType - http://grepcode.com/file/repo1.maven.org/maven2/org.apache.cassandra/cassandra-all/1.2.0-beta1/org/apache/cassandra/db/marshal/LocalByPartionerType.java?av=f
- InetAddressType - http://grepcode.com/file/repo1.maven.org/maven2/org.apache.cassandra/cassandra-all/1.2.0-beta1/org/apache/cassandra/db/marshal/InetAddressType.java?av=f
- EmptyType - http://grepcode.com/file/repo1.maven.org/maven2/org.apache.cassandra/cassandra-all/1.2.0-beta1/org/apache/cassandra/db/marshal/EmptyType.java?av=f
- ColumnToCollectionType - http://grepcode.com/file/repo1.maven.org/maven2/org.apache.cassandra/cassandra-all/1.2.0-beta1/org/apache/cassandra/db/marshal/ColumnToCollectionType.java?av=f

If anybody is interested in cutting their teeth on the FluentCassandra type system, the `EmptyType` seems like it would be relatively easy to implement. Given that it just produces an empty byte array.

**Comment by eplowe** [comment]
> LocalByPartitionerType - http://grepcode.com/file/repo1.maven.org/maven2/org.apache.cassandra/cassandra-all/1.2.0->beta1/org/apache/cassandra/db/marshal/LocalByPartionerType.java?av=f

According to the comments in the class:

_for sorting columns representing row keys in the row ordering as determined by a partitioner. Not intended for user-defined CFs, and will in fact error out if used with such._

EmptyType and ColumnToCollectionType can technically be defined, even though they aren't referenced on the cql_data_types documentation page. e.g.:

_ALTER TABLE table ADD empty_col 'EmptyType';
ALTER TABLE table ADD col_test 'ColumnToCollectionType';_

And based on peaking around the code, it seems ColumnToCollectionType is used internally to map a column to its proper collection type (map, list, set). But please take this with a grain of salt as I may have missed something.

This leaves InetAddressType -- you can define a column as 'inet' and according to: http://www.datastax.com/docs/1.2/cql_cli/cql_data_types

_inet   IP address string in xxx.xxx.xxx.xxx form. See 1).
1) Used by python-cql driver and binary protocols._

I would say it makes sense to implement InetAddressType as it is actually a CQL data type that is listed for use. Just my 2 cents.

**Comment by nberardi** [comment]
I would say `EmptyType` and `InetAddressType` are ones we are going to want to implement.  I have a feeling that `EmptyType` has a use in the `CompositeType`.

**Comment by nberardi** [comment]
Added the two types I was concerned about.
