### ISSUE TITLE
Exception after upgrading to version 1.2.0 (nuget)

### ISSUE THREAD

**Issue by IlyaGrebnov** [fluentcassandra/fluentcassandra#98]
I am getting following exception after upgrading to 1.2.0 using nuget:

FluentCassandra.Operations.CassandraOperationException: Invalid method name: 'execute_cql3_query' ---> FluentCassandra.Thrift.TApplicationException: Invalid method name: 'execute_cql3_query'

**Comment by nberardi** [comment]
What version of Cassandra are you using?

## 

Nick Berardi
(484) 302-0125
Sent on the go from my phone.

On Jan 3, 2013, at 7:20 PM, Ilya Grebnov notifications@github.com wrote:

I am getting following exception after upgrading to 1.2.0 using nuget:

FluentCassandra.Operations.CassandraOperationException: Invalid method
name: 'execute_cql3_query' --->
FluentCassandra.Thrift.TApplicationException: Invalid method name:
'execute_cql3_query'

—
Reply to this email directly or view it on
GitHubhttps://github.com/managedfusion/fluentcassandra/issues/98.

**Comment by IlyaGrebnov** [comment]
We are using Cassandra 1.1.6.

**Comment by nberardi** [comment]
Cassandra 1.2.0 changed how they are doing CQL, so I am trying to figure out the best way to support the different interfaces.  I thought I had figured it out but apparently not.

**Comment by eplowe** [comment]
Yeah -- CQL 3 was beta in versions leading up to 1.2. execute_cql3 doesn't
exist below 1.2. I saw you added a version check -- maybe we should look at
that and determine if we should use the regular execute_cql command if the
version if below the one needed. I think that should solve it.
